### ISSUE TITLE
LookupError: No FeatureType with the name Digital Currency Address - XBT found

### ISSUE THREAD

**Issue by 0xB10C** [0xB10C/ofac-sanctioned-digital-currency-addresses#12]
The nightly CI run of the tool fails with the following error:

```
  mkdir data
  python3 generate-address-list.py XBT ETH XMR LTC ZEC DASH BTG ETC BSV BCH XVG USDC USDT XRP TRX ARB BSC -f JSON TXT -path ./data
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.11.9/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.9/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.9/x64
    Python[2](https://github.com/0xB10C/ofac-sanctioned-digital-currency-addresses/actions/runs/8954302705/job/24593793734#step:6:2)_ROOT_DIR: /opt/hostedtoolcache/Python/[3](https://github.com/0xB10C/ofac-sanctioned-digital-currency-addresses/actions/runs/8954302705/job/24593793734#step:6:3).11.9/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.9/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.9/x6[4](https://github.com/0xB10C/ofac-sanctioned-digital-currency-addresses/actions/runs/8954302705/job/24593793734#step:6:4)/lib
Traceback (most recent call last):
  File "/home/runner/work/ofac-sanctioned-digital-currency-addresses/ofac-sanctioned-digital-currency-addresses/generate-address-list.py", line 109, in <module>
    main()
  File "/home/runner/work/ofac-sanctioned-digital-currency-addresses/ofac-sanctioned-digital-currency-addresses/generate-address-list.py", line 97, in main
    address_id = get_address_id(root, asset)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/ofac-sanctioned-digital-currency-addresses/ofac-sanctioned-digital-currency-addresses/generate-address-list.py", line 4[5](https://github.com/0xB10C/ofac-sanctioned-digital-currency-addresses/actions/runs/8954302705/job/24593793734#step:6:5), in get_address_id
    raise LookupError("No FeatureType with the name {} found".format(
LookupError: No FeatureType with the name Digital Currency Address - XBT found
Error: Process completed with exit code 1.
```

**Comment by 0xB10C** [comment]
The XML namespace in the `sdn_advanced.xml` changed:

```diff
< <Sanctions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Version="3" xsi:schemaLocation="https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML.xsd" xmlns="https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML">
---
> <Sanctions xmlns="http://www.un.org/sanctions/1.0" Version="3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.un.org/sanctions/1.0 http://www.treasury.gov/ofac/downloads/sanctions/1.0/sdn_advanced.xsd">
```

Since we hardcode the namespace, this broke.

https://github.com/0xB10C/ofac-sanctioned-digital-currency-addresses/blob/e8601228850ceaa45905c7861256f322ec4ff09d/generate-address-list.py#L9
